import { slugify } from "./utils";

export type ProductBadge = "BEST SELLER" | "PRO GRADE" | "NEW" | "HOT DEAL" | null;

export type SeedProduct = {
  sku: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  priceCents: number;
  originalPriceCents?: number;
  rating: number;
  reviewCount: number;
  badge: ProductBadge;
  shortDescription: string;
  description: string;
  specs: Record<string, string>;
  inStock: boolean;
  stockQty: number;
  imageUrl: string | null;
  replacementPartNumbers?: string[];
  source?: string;
};

const U = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=${w}`;

export const IMG = {
  heroConstruction: U("photo-1664312616511-81fe2e745cb3", 1920),
  dieselParts: U("photo-1638048035024-7df2b557e301", 1200),
  team: {
    michael: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    sarah: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    david: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    lisa: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
  },
} as const;

const IMG_VGT_TURBO = U("photo-1748851556700-560d9b7454ca");
const IMG_ENGINE_BLOCK = U("photo-1759794158429-c9e1b30a0486");
const IMG_FUEL_PUMP_HP = U("photo-1679712547753-eaaf4dad4af8");
const IMG_INJECTOR_SET6 = U("photo-1594506716333-739b5ed16672");
const IMG_AIR_FILTER = U("photo-1720929617042-ac3ea5a6d1e2");
const IMG_TURBO_REBUILD = U("photo-1549937536-477591b14d39");
const IMG_ENGINE_COMPONENTS = U("photo-1567177173026-402dd75a5ab7");
const IMG_COMMON_RAIL = U("photo-1777360207555-9a9610db8259");
const IMG_TURBO_T04 = U("photo-1716847018464-4e403c7a2ccd");
const IMG_TURBO_TF035 = U("photo-1682428606283-1b5fa429cc2b");
const IMG_TURBO_GT1241 = U("photo-1640769814685-67ac4d49a112");
const IMG_PRIMER_PUMP = U("photo-1661745805708-9c4a831545a7");
const IMG_FUEL_INJ_PUMP2 = U("photo-1565475243642-4ba46445cf21");
const IMG_TRANSFER_PUMP = U("photo-1581418412893-7bd90746381d");
const IMG_LIFT_PUMP = U("photo-1563207769-3343cb585fcb");
const IMG_INJ_KIT_KUBOTA = U("photo-1621235219059-1e4ba9a1041c");
const IMG_INJ_KIT_DOOSAN = U("photo-1537462715879-360eeb61a0ad");
const IMG_PENCIL_INJ = U("photo-1696514354993-9e4432e70615");
const IMG_GASKET_SET = U("photo-1531132204304-242e7c5309f4");
const IMG_OIL_COOLER = U("photo-1599256871871-847de7414abf");

function p(input: Omit<SeedProduct, "slug">): SeedProduct {
  return { ...input, slug: slugify(input.name) + "-" + input.sku.toLowerCase() };
}

export const SEED_PRODUCTS: SeedProduct[] = [
  p({
    sku: "GT3782VA",
    name: "VGT Turbocharger Assembly - High Performance",
    brand: "garrett",
    category: "turbochargers",
    priceCents: 124999,
    rating: 4.8,
    reviewCount: 127,
    badge: "BEST SELLER",
    shortDescription: "Variable geometry turbocharger assembly for heavy-duty applications.",
    description: "Premium VGT turbocharger engineered for sustained heavy-duty performance. Designed for diesel applications requiring precise boost control across the entire RPM range. Built with high-temperature alloys and includes all gaskets and mounting hardware.",
    specs: { "Compressor wheel": "Billet aluminum", "Turbine": "Inconel 713C", "Actuator": "Electronic", "Bearings": "360 deg thrust", "Warranty": "2 years" },
    inStock: true,
    stockQty: 24,
    imageUrl: IMG_VGT_TURBO,
  }),
  p({
    sku: "ISX15-BLK-2024",
    name: "Complete Diesel Engine Block",
    brand: "cummins",
    category: "engine-parts",
    priceCents: 389999,
    rating: 4.9,
    reviewCount: 89,
    badge: "PRO GRADE",
    shortDescription: "Cast iron engine block for ISX15 Cummins applications.",
    description: "Bare engine block for ISX15 platforms - machined and ready for assembly. Includes main caps and bolts.",
    specs: { "Material": "Gray cast iron", "Bore": "137mm", "Stroke": "169mm", "Application": "ISX15", "Condition": "Remanufactured" },
    inStock: true,
    stockQty: 5,
    imageUrl: IMG_ENGINE_BLOCK,
  }),
  p({
    sku: "0445010516",
    name: "High-Pressure Fuel Injection Pump",
    brand: "bosch",
    category: "fuel-pumps",
    priceCents: 89999,
    rating: 4.7,
    reviewCount: 203,
    badge: null,
    shortDescription: "Common-rail high-pressure pump rated to 1800 bar.",
    description: "Direct OEM replacement Bosch CP4 pump. Tested to OEM specs before shipment with a 24-month unlimited mileage warranty.",
    specs: { "Max pressure": "1800 bar", "Type": "CP4", "Mounting": "Gear driven", "Inlet": "M14x1.5", "Warranty": "2 years" },
    inStock: true,
    stockQty: 32,
    imageUrl: IMG_FUEL_PUMP_HP,
  }),
  p({
    sku: "28232248",
    name: "Premium Diesel Fuel Injectors (Set of 6)",
    brand: "delphi",
    category: "fuel-injectors",
    priceCents: 68999,
    rating: 4.6,
    reviewCount: 456,
    badge: "NEW",
    shortDescription: "Six-pack of premium common-rail injectors.",
    description: "Flow-matched and balanced set of six common-rail injectors. New, never rebuilt - full OEM replacement.",
    specs: { "Count": "6", "Type": "Common rail", "Hole count": "8", "Test": "Flow matched", "Warranty": "2 years" },
    inStock: true,
    stockQty: 18,
    imageUrl: IMG_INJECTOR_SET6,
  }),
  p({
    sku: "P608533",
    name: "Heavy-Duty Air Filter Assembly",
    brand: "donaldson",
    category: "engine-parts",
    priceCents: 18999,
    rating: 4.8,
    reviewCount: 178,
    badge: null,
    shortDescription: "Radial-seal air filter for severe-duty service.",
    description: "Donaldson radial-seal element for severe-duty diesel air intake systems. High efficiency cellulose media.",
    specs: { "Type": "Radial seal", "Media": "Cellulose", "Efficiency": "99.9%", "OD": "12.7 in", "Height": "16.3 in" },
    inStock: true,
    stockQty: 67,
    imageUrl: IMG_AIR_FILTER,
  }),
  p({
    sku: "TURBO-RBK-300",
    name: "Turbo Rebuild Kit - Complete",
    brand: "borgwarner",
    category: "turbochargers",
    priceCents: 32999,
    rating: 4.7,
    reviewCount: 312,
    badge: null,
    shortDescription: "Complete bearing and seal rebuild kit.",
    description: "Everything required to rebuild a BorgWarner turbocharger: thrust bearings, journal bearings, seal rings, O-rings, and detailed instructions.",
    specs: { "Includes": "All bearings, seals, rings", "Hardware": "Yes", "Instructions": "Included", "Warranty": "1 year" },
    inStock: true,
    stockQty: 45,
    imageUrl: IMG_TURBO_REBUILD,
  }),
  p({
    sku: "CAT-ENG-2500",
    name: "Precision Engine Components Set",
    brand: "caterpillar",
    category: "engine-parts",
    priceCents: 42999,
    rating: 4.8,
    reviewCount: 267,
    badge: null,
    shortDescription: "Genuine CAT precision engine components.",
    description: "Genuine Caterpillar precision component set for in-frame rebuilds. Includes pistons, rings, bearings, and gaskets.",
    specs: { "OEM": "Yes", "Application": "C15 / 3406E", "Warranty": "2 years" },
    inStock: true,
    stockQty: 12,
    imageUrl: IMG_ENGINE_COMPONENTS,
  }),
  p({
    sku: "BOSCH-CR-5000",
    name: "Common Rail Fuel System Kit",
    brand: "bosch",
    category: "fuel-pumps",
    priceCents: 167999,
    rating: 4.9,
    reviewCount: 145,
    badge: "HOT DEAL",
    shortDescription: "Complete common-rail fuel system overhaul kit.",
    description: "Complete Bosch common-rail kit: pump, rail, sensors, and lines. Save vs. piecing it together.",
    specs: { "System": "CRS3", "Pressure": "2500 bar", "Includes": "Pump, rail, sensors, lines", "Warranty": "2 years" },
    inStock: true,
    stockQty: 7,
    imageUrl: IMG_COMMON_RAIL,
  }),
  p({
    sku: "8981479061",
    name: "Turbo RHF55V Turbocharger for Isuzu 4HK1 Engine",
    brand: "isuzu",
    category: "turbochargers",
    priceCents: 56999,
    rating: 4.6,
    reviewCount: 89,
    badge: "BEST SELLER",
    shortDescription: "Direct fit RHF55V for Isuzu 4HK1.",
    description: "Direct replacement turbocharger for Isuzu 4HK1 engines. Bolt-on installation with all hardware included.",
    specs: { "Model": "RHF55V", "Application": "Isuzu 4HK1", "Warranty": "2 years" },
    inStock: true,
    stockQty: 19,
    imageUrl: IMG_VGT_TURBO,
  }),
  p({
    sku: "1806078C91",
    name: "Turbo T04B94 3LM-466 for CASE DT466 Engine",
    brand: "garrett",
    category: "turbochargers",
    priceCents: 29900,
    rating: 4.5,
    reviewCount: 67,
    badge: null,
    shortDescription: "Garrett T04B94 for International DT466 / CASE.",
    description: "Reliable Garrett T04B94 turbo for DT466 platform engines used in CASE equipment.",
    specs: { "Model": "T04B94 3LM-466", "Application": "DT466", "Warranty": "2 years" },
    inStock: true,
    stockQty: 22,
    imageUrl: IMG_TURBO_T04,
  }),
  p({
    sku: "1J773-17013",
    name: "Turbo TD04L4 for Kubota V3307 Engine",
    brand: "ihi",
    category: "turbochargers",
    priceCents: 27900,
    rating: 4.7,
    reviewCount: 124,
    badge: "PRO GRADE",
    shortDescription: "IHI TD04L4 turbo for Kubota V3307.",
    description: "Genuine IHI turbocharger for Kubota V3307 industrial engines. Drop-in replacement.",
    specs: { "Model": "TD04L4", "Application": "Kubota V3307", "Warranty": "2 years" },
    inStock: true,
    stockQty: 31,
    imageUrl: IMG_TURBO_REBUILD,
  }),
  p({
    sku: "49335-02532",
    name: "Turbo TF035HM for Kubota V3800 Engine",
    brand: "ihi",
    category: "turbochargers",
    priceCents: 20899,
    rating: 4.5,
    reviewCount: 93,
    badge: null,
    shortDescription: "TF035HM turbo for Kubota V3800.",
    description: "Compact TF035HM turbocharger sized for Kubota V3800 series engines.",
    specs: { "Model": "TF035HM", "Application": "Kubota V3800", "Warranty": "2 years" },
    inStock: true,
    stockQty: 28,
    imageUrl: IMG_TURBO_TF035,
  }),
  p({
    sku: "7030304",
    name: "Turbo GT1241Z for Doosan D24 Engine",
    brand: "garrett",
    category: "turbochargers",
    priceCents: 48565,
    rating: 4.6,
    reviewCount: 71,
    badge: "NEW",
    shortDescription: "Compact GT1241Z for Doosan D24.",
    description: "Brand new Garrett GT1241Z for the Doosan D24 engine series.",
    specs: { "Model": "GT1241Z", "Application": "Doosan D24", "Warranty": "2 years" },
    inStock: true,
    stockQty: 14,
    imageUrl: IMG_TURBO_GT1241,
  }),
  p({
    sku: "RE68345",
    name: "Fuel Pump for John Deere 3029/4039/4045 Engines",
    brand: "john-deere",
    category: "fuel-pumps",
    priceCents: 3450,
    rating: 4.7,
    reviewCount: 156,
    badge: "BEST SELLER",
    shortDescription: "Mechanical lift pump for Deere 3029/4039/4045.",
    description: "Direct fit lift pump for popular John Deere 3-cyl and 4-cyl engines. OEM equivalent.",
    specs: { "Application": "3029/4039/4045", "Type": "Mechanical", "Warranty": "1 year" },
    inStock: true,
    stockQty: 84,
    imageUrl: IMG_FUEL_PUMP_HP,
  }),
  p({
    sku: "6657734",
    name: "Fuel Primer Pump for Bobcat Skid Steers",
    brand: "bosch",
    category: "fuel-pumps",
    priceCents: 1255,
    rating: 4.6,
    reviewCount: 89,
    badge: null,
    shortDescription: "Primer pump for Bobcat skid steers.",
    description: "Hand-primer fuel pump assembly compatible with most Bobcat skid steer loader platforms.",
    specs: { "Type": "Hand primer", "Warranty": "1 year" },
    inStock: true,
    stockQty: 96,
    imageUrl: IMG_PRIMER_PUMP,
  }),
  p({
    sku: "446-5409",
    name: "Electric Fuel Transfer Pump 24V",
    brand: "caterpillar",
    category: "fuel-pumps",
    priceCents: 7890,
    rating: 4.5,
    reviewCount: 203,
    badge: null,
    shortDescription: "24V electric fuel transfer pump.",
    description: "Genuine CAT 24V electric transfer pump used across many CAT diesel engine platforms.",
    specs: { "Voltage": "24V", "Flow": "150 L/h", "Warranty": "1 year" },
    inStock: true,
    stockQty: 41,
    imageUrl: IMG_TRANSFER_PUMP,
  }),
  p({
    sku: "AM132715",
    name: "Mechanical Fuel Lift Pump",
    brand: "john-deere",
    category: "fuel-pumps",
    priceCents: 4599,
    rating: 4.4,
    reviewCount: 112,
    badge: null,
    shortDescription: "Direct fit mechanical lift pump.",
    description: "Mechanical lift pump for smaller John Deere and Kubota powered equipment.",
    specs: { "Type": "Mechanical", "Warranty": "1 year" },
    inStock: true,
    stockQty: 55,
    imageUrl: IMG_LIFT_PUMP,
  }),
  p({
    sku: "23670-E0400",
    name: "Fuel Injector for Hino J08E Engine",
    brand: "denso",
    category: "fuel-injectors",
    priceCents: 15680,
    rating: 4.7,
    reviewCount: 78,
    badge: "PRO GRADE",
    shortDescription: "Single common-rail injector for Hino J08E.",
    description: "Denso common-rail injector for the Hino J08E platform. Flow-tested before shipment.",
    specs: { "Application": "Hino J08E", "Test": "Flow matched", "Warranty": "2 years" },
    inStock: true,
    stockQty: 39,
    imageUrl: IMG_INJECTOR_SET6,
  }),
  p({
    sku: "7023120",
    name: "4Pcs Fuel Injector Set for Kubota V1903/V2003T",
    brand: "bosch",
    category: "fuel-injectors",
    priceCents: 9500,
    rating: 4.5,
    reviewCount: 145,
    badge: "BEST SELLER",
    shortDescription: "Set of 4 injectors for Kubota V1903/V2003T.",
    description: "Complete 4-injector set for Kubota V1903 and V2003T engines. Bosch quality.",
    specs: { "Count": "4", "Application": "Kubota V1903 / V2003T", "Warranty": "1 year" },
    inStock: true,
    stockQty: 28,
    imageUrl: IMG_INJ_KIT_KUBOTA,
  }),
  p({
    sku: "400903-00074D",
    name: "4Pcs Fuel Injector for Doosan D24 Engine",
    brand: "denso",
    category: "fuel-injectors",
    priceCents: 85200,
    rating: 4.6,
    reviewCount: 56,
    badge: null,
    shortDescription: "Doosan D24 common-rail injector set.",
    description: "Set of four common-rail injectors for the Doosan D24. Brand new OEM equivalent.",
    specs: { "Count": "4", "Application": "Doosan D24", "Warranty": "2 years" },
    inStock: true,
    stockQty: 9,
    imageUrl: IMG_INJ_KIT_DOOSAN,
  }),
  p({
    sku: "RE38087",
    name: "Pencil Fuel Injector for John Deere 4-Cylinder",
    brand: "john-deere",
    category: "fuel-injectors",
    priceCents: 10479,
    rating: 4.6,
    reviewCount: 167,
    badge: null,
    shortDescription: "Pencil injector for Deere 4-cyl engines.",
    description: "Pencil-style injector for older John Deere 4-cyl diesel engines. Direct replacement.",
    specs: { "Type": "Pencil", "Application": "Deere 4-cyl", "Warranty": "1 year" },
    inStock: true,
    stockQty: 48,
    imageUrl: IMG_PENCIL_INJ,
  }),
  p({
    sku: "7249380",
    name: "Common Rail Injector Kit for Bobcat",
    brand: "bosch",
    category: "fuel-injectors",
    priceCents: 124900,
    rating: 4.7,
    reviewCount: 42,
    badge: "HOT DEAL",
    shortDescription: "Common-rail injector kit for Bobcat.",
    description: "Bosch common-rail kit fits popular Bobcat compact equipment platforms.",
    specs: { "Application": "Bobcat", "Warranty": "2 years" },
    inStock: true,
    stockQty: 6,
    imageUrl: IMG_COMMON_RAIL,
  }),
  p({
    sku: "VR-HEAD-550",
    name: "Cylinder Head Gasket Set",
    brand: "mahle",
    category: "gaskets-seals",
    priceCents: 12499,
    rating: 4.5,
    reviewCount: 178,
    badge: null,
    shortDescription: "Complete head gasket set.",
    description: "MAHLE complete cylinder head gasket set with all required seals and rings.",
    specs: { "Includes": "Head gasket, valve seals, ring set", "Warranty": "1 year" },
    inStock: true,
    stockQty: 38,
    imageUrl: IMG_GASKET_SET,
  }),
  p({
    sku: "KOM-OC-6000",
    name: "Oil Cooler Assembly",
    brand: "mahle",
    category: "oil-pumps",
    priceCents: 24500,
    rating: 4.6,
    reviewCount: 92,
    badge: null,
    shortDescription: "Complete oil cooler assembly with mounting hardware.",
    description: "Complete oil cooler assembly for heavy-duty diesel applications. Includes mounting hardware and gaskets.",
    specs: { "Cores": "Aluminum", "Includes": "Gaskets + hardware", "Warranty": "1 year" },
    inStock: true,
    stockQty: 17,
    imageUrl: IMG_OIL_COOLER,
  }),
  p({
    sku: "ALT-24V-200A",
    name: "Heavy-Duty 24V 200A Alternator",
    brand: "delco-remy",
    category: "alternators",
    priceCents: 64900,
    rating: 4.8,
    reviewCount: 134,
    badge: "BEST SELLER",
    shortDescription: "24V 200-amp alternator.",
    description: "Heavy-duty 24V 200A alternator for severe-duty truck and equipment applications.",
    specs: { "Voltage": "24V", "Amps": "200A", "Warranty": "2 years" },
    inStock: true,
    stockQty: 26,
    imageUrl: IMG_ENGINE_COMPONENTS,
  }),
  p({
    sku: "STR-39MT-12V",
    name: "39MT 12V Heavy-Duty Starter",
    brand: "delco-remy",
    category: "starter-motors",
    priceCents: 49900,
    rating: 4.7,
    reviewCount: 211,
    badge: null,
    shortDescription: "Delco Remy 39MT 12V starter.",
    description: "12V planetary gear-reduction starter rated for severe-duty cranking.",
    specs: { "Voltage": "12V", "Type": "39MT", "Warranty": "2 years" },
    inStock: true,
    stockQty: 33,
    imageUrl: IMG_ENGINE_COMPONENTS,
  }),
  p({
    sku: "WP-CUM-6BT",
    name: "Cummins 6BT Water Pump",
    brand: "cummins",
    category: "water-pumps",
    priceCents: 18900,
    rating: 4.6,
    reviewCount: 287,
    badge: null,
    shortDescription: "OEM-spec water pump for Cummins 6BT.",
    description: "Direct fit water pump for Cummins 5.9L 6BT. Includes gasket.",
    specs: { "Application": "Cummins 6BT 5.9L", "Warranty": "2 years" },
    inStock: true,
    stockQty: 52,
    imageUrl: IMG_OIL_COOLER,
  }),
  p({
    sku: "BELT-MTI-PK",
    name: "Multi-Rib Drive Belt",
    brand: "gates",
    category: "belts-hoses",
    priceCents: 5499,
    rating: 4.7,
    reviewCount: 412,
    badge: null,
    shortDescription: "Heavy-duty multi-rib drive belt.",
    description: "Gates multi-rib drive belt engineered for high-load diesel accessory drives.",
    specs: { "Type": "Multi-rib", "Length": "varies", "Warranty": "1 year" },
    inStock: true,
    stockQty: 124,
    imageUrl: IMG_ENGINE_COMPONENTS,
  }),
];

export function getProductBySlug(slug: string) {
  return SEED_PRODUCTS.find((p) => p.slug === slug) ?? null;
}

export function getProductsByCategory(categorySlug?: string) {
  if (!categorySlug || categorySlug === "all") return SEED_PRODUCTS;
  return SEED_PRODUCTS.filter((p) => p.category === categorySlug);
}

export function getProductsByBrand(brandSlug: string) {
  return SEED_PRODUCTS.filter((p) => p.brand === brandSlug);
}
